### ISSUE TITLE
ddev configuration notes

### ISSUE THREAD

**Issue by catch56** [tag1consulting/google-drupal#16]
We need people to be able to run this locally, if only for development.

Since it's working with a ddev-enabled Drupal core git checkout, I'm not sure a repo is that useful, but we can at least document the ddev configuration.

.ddev/docker-compose.chromedriver.yml
```
version: '3.6'
services:
  chromedriver:
    container_name: ddev-${DDEV_SITENAME}-chromedriver
    image: drupalci/chromedriver:production
    volumes:
      - /dev/shm:/dev/shm
    labels:
    # These labels ensure this service is discoverable by ddev
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
  # This links the Chromedriver service to the web service defined
  # in the main docker-compose.yml, allowing applications running
  # in the web service to access the driver at `chromedriver`.
  web:
    links:
      - chromedriver:$DDEV_HOSTNAME
```

.ddev/docker-compose.jaeger.yml
```
version: '3.7'
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "6831:6831/udp"
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
    networks:
      - jaeger

networks:
  jaeger:
```

Add this to .ddev/config.yml:

```
web_environment:
  - "OTEL_COLLECTOR=http://jaeger:4318"
```

Jaeger UI should then be available at http://127.0.0.1:16686/ after a ddev restart. And running FunctionalPerformanceTests should result in telemetry being sent to Jaeger successfully.

**Comment by heddn** [comment]
For the chromedriver, I had to use. This increases the memory and adds an environment variable for finding the chromedriver server.

```
version: '3.6'
services:
  chromedriver:
    container_name: ddev-${DDEV_SITENAME}-chromedriver
    image: drupalci/chromedriver:production
    volumes:
      - /dev/shm:/dev/shm
    shm_size: 2gb
    labels:
    # These labels ensure this service is discoverable by ddev
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
  # This links the Chromedriver service to the web service defined
  # in the main docker-compose.yml, allowing applications running
  # in the web service to access the driver at `chromedriver`.
  web:
    links:
      - chromedriver:$DDEV_HOSTNAME
    environment:
      - MINK_DRIVER_ARGS_WEBDRIVER=["chrome", {"browserName":"chrome","chromeOptions":{"args":["--disable-gpu","--headless", "--no-sandbox"]}}, "http://chromedriver:9515"]
```

**Comment by catch56** [comment]
Non-working jaeger/elastic search config:
.ddev/docker-compose.elasticsearch.yml
```
version: '3.7'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
    environment:
      - "xpack.security.enabled=false"
      - "discovery.type=single-node"
    ports:
      - "9200:9200"
      - "9300:9300"
```

.ddev/docker-compose.jaeger.yml
```
version: '3.7'
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://127.0.0.1:9200
    ports:
      - "6831:6831/udp"
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
```
